### ISSUE TITLE
Text not properly positioned on screen

### ISSUE THREAD

**Issue by blenheim** [sumotoy/OLED_pictivaWide#1]
Hello, my name is Emanuele and I'm an amateur softwarist. First of all thanks for your great work with this library. I've tested most among your examples with Arduino ProMini and worked fine. The only issue I've found is that the text is not placed correctly on the screen. In fact usign the function oled.setCursor(0,0) I would expect the text is placed starting from top left corner of the screen and is contained within the screen. While the x position is properly set on left side, the y position is set higher and the font resulted to be cut.
Best regards.

**Comment by blenheim** [comment]
By the way, I've used the basic example supplied with the library (arial font).
Best regards

**Comment by sumotoy** [comment]
Hello,
I see, there's 1 pixel missed... This is weird because 0 it's the start row but probably I have to check initialization for offset the screen.
In the meantime load the last one, it has a temporary fix. I will fix this better but have to test with images and draw commands.
Cool it works with 8Bit CPU, I'm actually using ARM and never tested with arduino.

**Comment by blenheim** [comment]
Hello, I've tested it again it is better but the text appears to be still cut. It is very clear if you replace "Hello word" with numbers. 
Thanks for your work.

**Comment by sumotoy** [comment]
I just used the offset fix. The drawFastHLine was affected as well as I was suppose. I've just tested it and looks good even with numbers.
Have you connected the RST wire? If not, you will need a complete power/off -> On of the display.
Just updated last beta.
the changed code is in _includes/SSD0332_registers.h
and OLED_pictivaWide.cpp
No other code modified.

**Comment by blenheim** [comment]
Yes, the reset is connected. I've also tried to power off/on the board but is the same. Other sketches like vumeter works perfectly.
It is tricky..

**Comment by sumotoy** [comment]
Mmmm... Maybe arduino it's caching compiled code.
Try this:

put just after oled.begin();
oled.drawFastHLine(0,0,287,0xFF);
Do not put any other command and leave the loop empty. You should see a line on the top of the screen, if not, try close arduino ide, substitute the whole library with the last one and reopen IDE.

**Comment by sumotoy** [comment]
The worst scenario is that your display has a small design differences from mine, in that case you can open:
_includes/SSD0332_registers.h
and change OP_OFFSET from -1 to -2 (or -3, try one by one)
Check by using 
oled.drawFastHLine(0,0,287,0xFF);
in a sketch...

**Comment by blenheim** [comment]
About your first suggestion, after downloading the sketch I have an straight line at the top of the screen.
I will try to follow your next suggestion.

**Comment by sumotoy** [comment]
Ok, this is a good sign, text and draw commands uses the same addressing space. So text should be ok now?

**Comment by blenheim** [comment]
No, text is still cut. Should I try  to change the offset?

**Comment by blenheim** [comment]
Now it is ok. I will do some more tests tomorrow and will let you have a feedback.
Many thanks for your support.
Best regards,
Emanuele

**Comment by sumotoy** [comment]
I'm pretty sure there's an issue with Arduino PROGMEM that cause an offset with font heigh on 8 bit avr.
the oled.drawFastHLine(0,0,287,0xFF); write a line on the top of the screen at pixel 0 (y), this command obviously doesn't use PROGMEM but font yes and with ARM it's correct since it doesn't use PROGMEM.
If you changed OP_OFFSET less than -1 you probably now have offset all the display, when I have time I will build a simple AVR board and check this
